config/routes.rb
Rails.application.routes.draw do
	resources :artists, only: [:index, :show], param: :name
	root "artists#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
# frozen_string_literal: true

class ArtistsController < ApplicationController
  def show
    service = LastFmFinder.new(params['page'])
    @tracks = service.get_top_tracks(params['name'])
    @summary = service.summary
  end

  def index
    service = LastFmFinder.new(params['page'])
    @artists = service.get_top_artists(params['country'])
    @summary = service.summary
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
# frozen_string_literal: true

module ArtistsHelper
  def show_artist(summary)
    summary['artist'] if summary
  end

  def show_country(summary)
    summary['country'] if summary
  end

  def paginate(summary)
    Paginator.new(summary, request.path, action_name).paginate
  end
end

app/views/artists/_search.html.erb
<%= form_tag root_path, method: "get" do %>
	<%= label_tag :top_artist_by_country %>
	<%= text_field_tag 'country', nil, placeholder: 'Enter country name here...'%>
	<%= submit_tag "Search", name: nil %>
<% end %>

app/views/artists/index.html.erb
<%= render "search" %>
<% if !@artists.blank? %>

	<h1><%= show_country(@summary) %> Top Artists</h1>

	<table width="100%">
		<% @artists.each do |artist| %>
			<tr>
				<td><%= artist['name'] %></td>
				<td><%= link_to image_tag(artist['image'].first['#text'], alt: "more info"), artist_path(artist['name']) %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="2"><%= paginate(@summary) %></td>
		</tr>
	</table>
<% end %>

app/views/artists/show.html.erb
<%= render "search" %>
<% if !@tracks.blank? %>
	<h1><%= show_artist(@summary) %> Top Tracks</h1>

	<table width="100%">
		<% @tracks.each do |track| %>
			<tr>
				<td>#<%= track["@attr"]['rank'] %></td>
				<td><%= track['name'] %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="2"><%= paginate(@summary) %></td>
		</tr>
	</table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TopArtists</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>